// @ts-nocheck

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { sendRewardRedemptionNotification } from '../_shared/services/notification-sender.ts'

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
}

interface RedeemRequest {
  reward_id: string
  student_id: string
}

Deno.serve(async (req: Request) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: CORS_HEADERS })
  }

  try {
    const { reward_id, student_id }: RedeemRequest = await req.json()

    if (!reward_id || !student_id) {
      return new Response(
        JSON.stringify({ error: 'Missing reward_id or student_id' }),
        { status: 400, headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' } }
      )
    }

    // Create Supabase client with service role
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    const supabase = createClient(supabaseUrl, supabaseServiceKey)

    // 1. Get reward details
    const { data: reward, error: rewardError } = await supabase
      .from('rewards')
      .select('*')
      .eq('id', reward_id)
      .eq('active', true)
      .single()

    if (rewardError || !reward) {
      return new Response(
        JSON.stringify({ error: 'Reward not found or inactive' }),
        { status: 404, headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' } }
      )
    }

    // 2. Check stock
    if (reward.stock !== null && reward.stock <= 0) {
      return new Response(
        JSON.stringify({ error: 'Reward out of stock' }),
        { status: 400, headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' } }
      )
    }

    // 3. Get student's total points
    const { data: pointsData, error: pointsError } = await supabase
      .from('points')
      .select('points')
      .eq('student_id', student_id)

    if (pointsError) {
      return new Response(
        JSON.stringify({ error: 'Failed to get student points' }),
        { status: 500, headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' } }
      )
    }

  const totalPoints = (pointsData ?? []).reduce((sum: number, entry: { points: number }) => sum + entry.points, 0)

    // 4. Check sufficient points
    if (totalPoints < reward.points_cost) {
      return new Response(
        JSON.stringify({ 
          error: 'Insufficient points',
          required: reward.points_cost,
          available: totalPoints
        }),
        { status: 400, headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' } }
      )
    }

    // 5. Create redemption (code generated by DEFAULT)
    const { data: redemption, error: redemptionError } = await supabase
      .from('redemptions')
      .insert({
        student_id,
        reward_id,
        points_spent: reward.points_cost,
        status: 'pending',
        expires_at: reward.expiry_days 
          ? new Date(Date.now() + reward.expiry_days * 24 * 60 * 60 * 1000).toISOString()
          : null,
        metadata: {
          reward_name: reward.name,
          brand: reward.brand,
        }
      })
      .select()
      .single()

    if (redemptionError) {
      console.error('Redemption creation error:', redemptionError)
      return new Response(
        JSON.stringify({ error: 'Failed to create redemption', details: redemptionError.message }),
        { status: 500, headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' } }
      )
    }

    // 6. Deduct points
    const { error: pointsDeductError } = await supabase
      .from('points')
      .insert({
        student_id,
        points: -reward.points_cost,
        transaction_type: 'redemption',
        reference_id: redemption.id,
        description: `Redeemed: ${reward.name}`,
        metadata: {
          reward_id,
          reward_name: reward.name,
          brand: reward.brand,
        }
      })

    if (pointsDeductError) {
      console.error('Points deduction error:', pointsDeductError)
      // Rollback redemption
      await supabase.from('redemptions').delete().eq('id', redemption.id)
      
      return new Response(
        JSON.stringify({ error: 'Failed to deduct points' }),
        { status: 500, headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' } }
      )
    }

    // 7. Update reward stock
    if (reward.stock !== null) {
      await supabase
        .from('rewards')
        .update({ stock: reward.stock - 1 })
        .eq('id', reward_id)
    }

    // Attempt to send reward redemption notification (non-blocking)
    try {
      const supabaseEnvUrl = Deno.env.get('SUPABASE_URL')
      const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')
      const fallbackExpiry = reward.expiry_days
        ? new Date(Date.now() + reward.expiry_days * 24 * 60 * 60 * 1000).toISOString()
        : null

      if (supabaseEnvUrl && serviceRoleKey) {
        await sendRewardRedemptionNotification(
          supabaseEnvUrl,
          serviceRoleKey,
          student_id,
          reward.name,
          redemption.redemption_code ?? '',
          redemption.expires_at ?? fallbackExpiry ?? new Date().toISOString()
        )
      } else {
        console.warn('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY, skipping reward notification')
      }
    } catch (notificationError) {
      console.error('Failed to send reward notification:', notificationError)
    }

    // Success response
    return new Response(
      JSON.stringify({
        success: true,
        redemption: {
          id: redemption.id,
          redemption_code: redemption.redemption_code,
          reward_name: reward.name,
          brand: reward.brand,
          points_cost: reward.points_cost,
          status: redemption.status,
          expires_at: redemption.expires_at,
        },
        remaining_points: totalPoints - reward.points_cost,
      }),
      { status: 200, headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' } }
    )

  } catch (error) {
    console.error('Redeem reward error:', error)
    const message = error instanceof Error ? error.message : 'Unknown error'
    return new Response(
      JSON.stringify({ error: 'Internal server error', details: message }),
      { status: 500, headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' } }
    )
  }
})
